const menuBtn=document.querySelector('.menu-btn');const nav=document.querySelector('.nav');if(menuBtn&&nav){menuBtn.addEventListener('click',()=>{nav.classList.toggle('open');menuBtn.setAttribute('aria-expanded',nav.classList.contains('open')?'true':'false');});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menuBtn.setAttribute('aria-expanded','false');}));}

const betaFormMarkup=(type='traveler')=>`<form class="beta-form" data-beta-form><input type="hidden" name="type" value="${type}"><div class="form-grid"><label>Full name<input name="name" type="text" autocomplete="name" required maxlength="120" placeholder="Your name"></label><label>Email address<input name="email" type="email" autocomplete="email" required maxlength="254" placeholder="you@example.com"></label><label>City or country<input name="city" type="text" autocomplete="address-level2" maxlength="120" placeholder="Utrecht, Netherlands"></label><label>Organization <span class="muted">(optional)</span><input name="organization" type="text" maxlength="160" placeholder="Business or community name"></label></div><label>Why are you interested in UNIGO? <span class="muted">(optional)</span><textarea name="message" maxlength="2000" rows="4" placeholder="Tell us what you would like to explore, contribute or test."></textarea></label><label class="consent-row"><input name="consent" type="checkbox" required> <span>I agree that UNIGO may store my details and contact me about the beta. I can unsubscribe at any time.</span></label><button class="btn primary" type="submit">Submit</button><p class="form-status" role="status" aria-live="polite"></p></form>`;

const homeLead=document.querySelector('.lead-form');if(homeLead&&!homeLead.querySelector('[data-beta-form]')){homeLead.innerHTML=betaFormMarkup('traveler');}
document.querySelectorAll('a[href*="docs.google.com/forms"]').forEach(link=>{link.removeAttribute('target');link.removeAttribute('rel');link.href=link.closest('section')?.id==='join'?'#join':'apply.html';});

document.querySelectorAll('[data-beta-form]').forEach(form=>{form.addEventListener('submit',async e=>{e.preventDefault();const status=form.querySelector('.form-status');const button=form.querySelector('button[type="submit"]');status.className='form-status';status.textContent='Submitting…';button.disabled=true;const payload=Object.fromEntries(new FormData(form).entries());payload.consent=form.elements.consent.checked;try{const response=await fetch('/api/beta-signup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Unable to submit your signup');status.classList.add('success');status.textContent='Saved. Redirecting…';window.location.href='thank-you.html';}catch(error){status.classList.add('error');status.textContent=error.message||'Something went wrong. Please try again.';button.disabled=false;}});});

const heroPassport=document.querySelector('.hero .phone-card');if(heroPassport&&!heroPassport.matches('a')){heroPassport.style.cursor='pointer';heroPassport.setAttribute('role','link');heroPassport.setAttribute('tabindex','0');const go=()=>window.location.href='impact-passport.html';heroPassport.addEventListener('click',go);heroPassport.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go();}});}

document.querySelectorAll('.passport-card .badges span').forEach(b=>{if(b.textContent.trim()==='Canal Cleaner')b.textContent='Circular Explorer';});
const addFaqLink=(container,beforeSelector)=>{if(!container||container.querySelector('a[href="faq.html"]'))return;const link=document.createElement('a');link.href='faq.html';link.textContent='FAQ';const before=beforeSelector?container.querySelector(beforeSelector):null;if(before)container.insertBefore(link,before);else container.appendChild(link);};addFaqLink(document.querySelector('.nav'),'.nav-cta');addFaqLink(document.querySelector('.footer-links'),'a[href="privacy.html"]');

const mobileStyle=document.createElement('style');mobileStyle.textContent=`.reveal{opacity:1;transform:none}.menu-btn{min-width:44px;min-height:44px}.btn,a,button{-webkit-tap-highlight-color:transparent}.beta-form input,.beta-form select,.beta-form textarea{font-size:16px}.site-header{padding-top:max(14px,env(safe-area-inset-top));padding-left:max(5%,env(safe-area-inset-left));padding-right:max(5%,env(safe-area-inset-right))}@media(max-width:900px){.nav.open{max-height:calc(100dvh - 72px);overflow-y:auto;overscroll-behavior:contain}.nav.open a{min-height:48px;display:flex;align-items:center}.menu-btn{touch-action:manipulation}}@media(max-width:700px){.hero-actions .btn{width:100%}.proof-strip span{text-align:center}.footer-links{grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.phone-top{gap:10px}.phone-top span:first-child{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.consent-row{font-size:14px}.section{padding-left:max(5%,env(safe-area-inset-left));padding-right:max(5%,env(safe-area-inset-right));}.premium-panel{margin-left:0;margin-right:0}}@media(max-width:380px){h1{font-size:42px;letter-spacing:-.05em}h2{font-size:34px}.section{padding-top:48px;padding-bottom:48px}.phone-card,.lead-form,.dashboard-card,.audience-card{padding:18px}.eyebrow{letter-spacing:.13em}.proof-strip span{font-size:14px}.brand{gap:8px}.brand span{font-size:14px}.brand img{max-width:105px}.score-display strong{font-size:62px}}@media(max-height:500px) and (orientation:landscape){.nav.open{max-height:calc(100dvh - 60px)}.premium-hero{padding-top:40px;padding-bottom:40px}}`;document.head.appendChild(mobileStyle);

const revealItems=document.querySelectorAll('.reveal');if('IntersectionObserver'in window&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches){revealItems.forEach(item=>{item.style.opacity='0';item.style.transform='translateY(20px)'});const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.style.opacity='1';entry.target.style.transform='none';observer.unobserve(entry.target);}});},{threshold:.08,rootMargin:'0px 0px -20px'});revealItems.forEach(item=>observer.observe(item));}else{revealItems.forEach(item=>item.classList.add('visible'));}